package stats

import (
	"flag"
	"os"
)

type StatsSettings struct {
	StatFile string

	Verbose bool
}

var Settings StatsSettings = StatsSettings{}

func init() {
	if len(os.Args) < 2 || os.Args[1] != "stats" {
		return
	}

	flag.StringVar(&Settings.StatFile, "f", "", "Path to stats file generated by Gor replay server")

	flag.BoolVar(&Settings.Verbose, "verbose", false, "Log requests")
}
